(** * ClassicalLemmas.chains — finitely supported chains over a ring

    For a finite type [cell] of cells and a ring [R], a chain is a finitely
    supported function [cell -> R], i.e. a finite function.  mathcomp already
    equips [{ffun cell -> R^o}] with its [lmodType R] structure, so sums and
    scalar multiples come for free; this file only adds the basis chains [cc x]
    and the linear extension [lin f] of a map [f] defined on cells, together
    with the lemmas needed to reason "cell by cell". *)

(** ** Provenance, sources, and what corresponds to what

    HOW THIS FILE WAS OBTAINED.  It was written with Claude Code (Anthropic),
    driving Rocq interactively through the rocq-mcp-evolve MCP server ("build"
    to list the open goals of a file, "open"/"step"/"try"/"check" to drive a
    single proof), so that a failing tactic was diagnosed on the spot instead
    of by recompiling.  rocq-mcp-evolve is developed by the LLM4Rocq project,
    https://github.com/LLM4Rocq/rocq-mcp-evolve (Apache-2.0; the opam package
    still carries its former slug LLM4Rocq/rocq-tools); it is gratefully
    acknowledged here.  Every error that recurred, together with the tactic
    that fixed it, is recorded in tactics-playbook.md at the root of the
    repository.  No result is admitted: "Print Assumptions" on the results of
    this file answers "Closed under the global context".

    MODELS AND ESTIMATED TOKEN COST FOR THIS FILE.

        Claude Fable 5.1     62k tokens   (09-14 21:49 -> 09-14 21:57 UTC)
        Claude Opus 5       139k tokens   (09-15 08:03 -> 09-15 14:50 UTC)
        TOTAL               201k tokens   of which 47k were output

      Method: the figures are estimated from the logs of the Claude Code
      session of 14-15 September 2026.  For every assistant message they count
      input + cache-creation + output tokens, i.e. the tokens processed anew,
      excluding the cached conversation that is re-read at each turn (772M
      over the project); a message is charged to the file its tool calls were
      acting on.  Three whole-session context rebuilds (compaction or resume),
      1.61M tokens in all, are charged to no file.  Project totals: 4.10M
      tokens of per-file work, 1.61M of context rebuilds, 5.70M overall.

    SOURCES.

      [M14]  F. Meunier, "Simplotopal maps and necklace splitting",
             Discrete Mathematics 323 (2014) 14-26.
             Local copy: classical-lemmas/Meunier2014-Simplotopal_Necklace_web.pdf

    WHAT CORRESPONDS TO WHAT.

      This file carries no statement of a paper; it is the algebraic
      infrastructure on which the whole of [M14, Section 2] is written, namely
      free modules of chains over the cells of a complex.

      - [M14, Sect. 2.2], "C_d(S) is the free module generated by the oriented
        d-simplotopes of S", and the chain maps of Sect. 2.5
                                    -> cc (basis chains), lin (linear extension
                                       of a map defined on cells), linD, linZ,
                                       linB, lin_sum, lin_comp
      - the principle, used implicitly throughout [M14, Sect. 2], that two
        additive homogeneous maps agreeing on the cells are equal
                                    -> chain_ext
      - the sign-reversing-involution arguments behind the two proofs of
        "d o d = 0" ([M14, Lemma 2.2] and its cubical analogue), written so as
        to stay valid in characteristic 2
                                    -> sum_pair_anti, sum_invol
      - augmentation bookkeeping used by [M14, Lemma 2.1] in dimension 1
                                    -> aug_lin, aug_bigsum, sum_cc_aug *)

From mathcomp Require Import all_boot all_algebra.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GRing.Theory.
Local Open Scope ring_scope.

Section Chains.
Variables (R : nzRingType) (cell : finType).

Local Notation chain := ({ffun cell -> R^o}).

(** The basis chain of a cell. *)
Definition cc (x : cell) : chain := [ffun y => (y == x)%:R].

Lemma ccE x y : cc x y = (y == x)%:R.
Proof. by rewrite ffunE. Qed.

Lemma chain_decomp (c : chain) : c = \sum_(x : cell) c x *: cc x.
Proof.
apply/ffunP => y; rewrite sum_ffunE (bigD1 y) //= !ffunE eqxx.
rewrite /GRing.scale /= mulr1 big1 ?addr0 // => x /negbTE neq.
by rewrite /ffun_scale !ffunE /GRing.scale /= eq_sym neq mulr0.
Qed.

Section Lin.
Variable (cell' : finType).

(** Linear extension of a map defined on cells. *)
Definition lin (f : cell -> {ffun cell' -> R^o}) (c : chain) : {ffun cell' -> R^o} :=
  \sum_(x : cell) c x *: f x.

Variable (f : cell -> {ffun cell' -> R^o}).

Lemma lin_cc x : lin f (cc x) = f x.
Proof.
rewrite /lin (bigD1 x) //= ffunE eqxx scale1r big1 ?addr0 // => y /negbTE neq.
by rewrite ffunE neq scale0r.
Qed.

Lemma linD c1 c2 : lin f (c1 + c2) = lin f c1 + lin f c2.
Proof.
by rewrite /lin -big_split; apply: eq_bigr => x _; rewrite ffunE scalerDl.
Qed.

Lemma linZ a c : lin f (a *: c) = a *: lin f c.
Proof.
by rewrite /lin scaler_sumr; apply: eq_bigr => x _; rewrite ffunE scalerA.
Qed.

Lemma linN c : lin f (- c) = - lin f c.
Proof. by rewrite -scaleN1r linZ scaleN1r. Qed.

Lemma linB c1 c2 : lin f (c1 - c2) = lin f c1 - lin f c2.
Proof. by rewrite linD linN. Qed.

Lemma lin0 : lin f 0 = 0.
Proof. by rewrite -(scale0r 0) linZ scale0r. Qed.

Lemma lin_sum (I : Type) (r : seq I) (F : I -> chain) :
  lin f (\sum_(i <- r) F i) = \sum_(i <- r) lin f (F i).
Proof. by elim/big_rec2: _ => [|i c1 c2 _ <-]; rewrite ?lin0 ?linD. Qed.

Lemma linE c : lin f c = \sum_(x : cell) c x *: f x.
Proof. by []. Qed.

End Lin.

(** Two maps that are additive, homogeneous and agree on cells agree everywhere. *)
Lemma chain_ext (cell' : finType) (F G : chain -> {ffun cell' -> R^o}) :
  (forall c1 c2, F (c1 + c2) = F c1 + F c2) ->
  (forall a c, F (a *: c) = a *: F c) ->
  (forall c1 c2, G (c1 + c2) = G c1 + G c2) ->
  (forall a c, G (a *: c) = a *: G c) ->
  (forall x, F (cc x) = G (cc x)) -> forall c, F c = G c.
Proof.
move=> FD FZ GD GZ FG c; rewrite [c]chain_decomp.
have sumF : forall (r : seq cell) (H : cell -> chain),
    F (\sum_(x <- r) H x) = \sum_(x <- r) F (H x).
  move=> r H; elim/big_rec2: _ => [|x c1 c2 _ <-]; last by rewrite FD.
  by rewrite -(scale0r 0) FZ scale0r.
have sumG : forall (r : seq cell) (H : cell -> chain),
    G (\sum_(x <- r) H x) = \sum_(x <- r) G (H x).
  move=> r H; elim/big_rec2: _ => [|x c1 c2 _ <-]; last by rewrite GD.
  by rewrite -(scale0r 0) GZ scale0r.
by rewrite sumF sumG; apply: eq_bigr => x _; rewrite FZ GZ FG.
Qed.

End Chains.

(** A double sum of an antisymmetric family vanishes — over ANY ring (the
    pairing is term-by-term, so this does not divide by 2).  [rnk] supplies a
    total order on the index type. *)
Lemma sum_pair_anti (I : finType) (M : zmodType) (rnk : I -> nat)
    (F : I -> I -> M) :
  injective rnk ->
  (forall i, F i i = 0) -> (forall i j, F i j = - F j i) ->
  \sum_(i : I) \sum_(j : I) F i j = 0.
Proof.
move=> rnk_inj Fdiag Fanti.
rewrite pair_big /=.
rewrite (bigID (fun q : I * I => (rnk q.2 < rnk q.1)%N)) /=.
rewrite [X in _ + X](reindex_inj (h := fun q : I * I => (q.2, q.1))); last first.
  by move=> [a b] [a' b'] [] -> ->.
rewrite [X in _ + X](eq_bigr (fun q : I * I => - F q.1 q.2)); last first.
  by move=> q _ /=; rewrite Fanti.
rewrite [X in _ + X]sumrN.
apply/eqP; rewrite subr_eq0; apply/eqP.
rewrite [in RHS]big_mkcond [in LHS]big_mkcond; apply: eq_bigr => q _ /=.
case: (ltngtP (rnk q.2) (rnk q.1)) => h.
- by [].
- by [].
- by move/rnk_inj: h => ->; rewrite Fdiag.
Qed.

Arguments cc {R cell} x.
Arguments lin {R cell cell'} f c.

Lemma lin_comp (R : nzRingType) (cell cell' cell'' : finType) (f : cell -> {ffun cell' -> R^o})
    (g : cell' -> {ffun cell'' -> R^o}) (c : {ffun cell -> R^o}) :
  lin g (lin f c) = lin (fun x => lin g (f x)) c.
Proof.
rewrite [lin f c]linE lin_sum; apply: eq_bigr => x _.
by rewrite linZ.
Qed.


Lemma scale_ffunE (R : nzRingType) (cell : finType) (a : R)
    (f : {ffun cell -> R^o}) (x : cell) : (a *: f) x = a * f x.
Proof. by rewrite ffunE. Qed.

(** Two linear extensions agreeing on the support of a chain agree on it. *)
Lemma lin_eq_supp (R : nzRingType) (cell cell' : finType)
    (f g : cell -> {ffun cell' -> R^o}) (c : {ffun cell -> R^o}) :
  (forall x, c x != 0 -> f x = g x) -> lin f c = lin g c.
Proof.
move=> h; rewrite /lin; apply: eq_bigr => x _.
by case: (altP (c x =P 0)) => [->|hx]; rewrite ?scale0r ?h.
Qed.

(** A chain supported on a single cell is a multiple of its basis chain. *)
Lemma chain_supp1 (R : nzRingType) (cell : finType)
    (z : {ffun cell -> R^o}) (x : cell) :
  (forall y, z y != 0 -> y = x) -> z = z x *: cc x.
Proof.
move=> h; apply/ffunP => y; rewrite scale_ffunE ccE.
case: (eqVneq y x) => [->|yx]; first by rewrite mulr1.
rewrite mulr0; apply/eqP; apply: contraT => hy.
by move: (h y hy) => e; rewrite e eqxx in yx.
Qed.

(** [lin f] commutes with a filtered sum. *)
Lemma lin_sum_cond (R : nzRingType) (cell cell' I : finType)
    (f : cell -> {ffun cell' -> R^o}) (P : pred I) (F : I -> {ffun cell -> R^o}) :
  lin f (\sum_(i | P i) F i) = \sum_(i | P i) lin f (F i).
Proof.
rewrite big_mkcond lin_sum [RHS]big_mkcond.
by apply: eq_bigr => i _; case: (P i); rewrite ?lin0.
Qed.

(** Cancellation by a sign-reversing involution — valid over ANY ring (the two
    halves are reindexed one onto the other, nothing is divided by 2). *)
Lemma sum_invol (I : finType) (Mo : zmodType) (P : pred I) (tau : I -> I)
    (F : I -> Mo) :
  (forall i, P i -> P (tau i)) -> (forall i, P i -> tau (tau i) = i) ->
  (forall i, P i -> F (tau i) = - F i) -> (forall i, P i -> tau i != i) ->
  \sum_(i | P i) F i = 0.
Proof.
move=> tP tt tF tne.
pose t i := if P i then tau i else i.
have tinv : forall i, t (t i) = i.
  move=> i; rewrite /t; case hi : (P i); last by rewrite hi.
  by rewrite (tP i hi) (tt i hi).
have tinj : injective t by apply: (can_inj (g := t)).
pose rk (i : I) := val (enum_rank i).
have rkinj : injective rk by move=> a b /val_inj/enum_rank_inj.
have hne : forall i, P i -> (rk i != rk (t i)).
  move=> i hi; apply/eqP => e.
  move: (tne i hi); rewrite -(_ : t i = tau i); last by rewrite /t hi.
  by rewrite -(rkinj _ _ e) eqxx.
rewrite (bigID (fun i => (rk i < rk (t i))%N)) /=.
rewrite [X in _ + X](eq_bigl (fun i => P i && (rk (t i) < rk i)%N)); last first.
  move=> i /=; case hi : (P i) => //=.
  case: (ltngtP (rk i) (rk (t i))) => // /rkinj e.
  by move: (hne i hi); rewrite -e eqxx.
rewrite [X in _ + X](reindex_inj tinj) /=.
rewrite [X in _ + X](eq_bigl (fun i => P i && (rk i < rk (t i))%N)); last first.
  move=> i /=; rewrite tinv; congr (_ && _).
  by rewrite /t; case hi : (P i); rewrite ?hi // (tP i hi).
rewrite [X in _ + X](eq_bigr (fun i => - F i)); last first.
  by move=> i /andP[hi _]; rewrite /t hi tF.
by rewrite sumrN subrr.
Qed.

Lemma lin_cc_id (R : nzRingType) (cell : finType) (c : {ffun cell -> R^o}) :
  lin cc c = c.
Proof. by rewrite /lin -chain_decomp. Qed.

(** augmentation of a basis chain and of a combination of basis chains *)
Lemma sum_cc_aug (R : nzRingType) (cell : finType) (x : cell) :
  \sum_(y : cell) (cc x : {ffun cell -> R^o}) y = 1.
Proof.
by rewrite (bigD1 x) //= ccE eqxx big1 ?addr0 // => y h; rewrite ccE (negbTE h).
Qed.

Lemma aug_bigsum (R : nzRingType) (cell I : finType) (P : pred I)
    (F : I -> cell) (b : I -> R) :
  \sum_(y : cell) ((\sum_(i | P i) b i *: cc (F i)) : {ffun cell -> R^o}) y
  = \sum_(i | P i) b i.
Proof.
rewrite (eq_bigr (fun y => \sum_(i | P i) (b i *: (cc (F i) : {ffun cell -> R^o})) y));
  last by move=> y _; rewrite sum_ffunE.
rewrite exchange_big /=; apply: eq_bigr => i _.
rewrite (eq_bigr (fun y => b i * (cc (F i) : {ffun cell -> R^o}) y)); last first.
  by move=> y _; rewrite scale_ffunE.
by rewrite -mulr_sumr sum_cc_aug mulr1.
Qed.

(** a cell in the support of a sum is in the support of one summand *)
Lemma supp_bigsum (R : nzRingType) (cell I : finType) (P : pred I)
    (F : I -> {ffun cell -> R^o}) (c : cell) :
  ((\sum_(i | P i) F i) c != 0) -> exists2 i, P i & (F i) c != 0.
Proof.
move=> h; case: (boolP [exists i, P i && (F i c != 0)]).
  by move=> /existsP[i /andP[hi hc]]; exists i.
move/existsPn => hno; exfalso; move/eqP: h; apply.
rewrite sum_ffunE big1 // => i hi.
by apply/eqP; move: (hno i); rewrite negb_and hi /= negbK.
Qed.

Lemma aug_lin (R : nzRingType) (cell cell' : finType)
    (f : cell -> {ffun cell' -> R^o}) (x : {ffun cell -> R^o}) :
  \sum_(y : cell') (lin f x) y = \sum_(c : cell) x c * (\sum_(y : cell') (f c) y).
Proof.
rewrite /lin (eq_bigr (fun y => \sum_(c : cell) (x c *: f c) y));
  last by move=> y _; rewrite sum_ffunE.
rewrite exchange_big /=; apply: eq_bigr => c _.
rewrite mulr_sumr; apply: eq_bigr => y _.
by rewrite scale_ffunE.
Qed.

Lemma lin_supp (R : nzRingType) (cell cell' : finType)
    (f : cell -> {ffun cell' -> R^o}) (x : {ffun cell -> R^o}) (y : cell') :
  (lin f x) y != 0 -> exists2 c, x c != 0 & (f c) y != 0.
Proof.
rewrite /lin => /supp_bigsum[c _ hc]; exists c.
  by apply: contraNN hc => /eqP e; rewrite e scale0r ffunE eqxx.
by apply: contraNN hc => /eqP e; rewrite scale_ffunE e mulr0 eqxx.
Qed.
