#!/usr/bin/env python3
"""Generate a runnable, self-contained milestone workflow wrapper — no runtime `args`.

Runtime `args` are NOT reliably delivered to Workflow scripts in this harness, so instead of
hand-embedding rows we GENERATE a wrapper: take the canonical template
(area_milestone_pipeline.workflow.js), and replace the marked <<MILESTONE-SPEC>> block with an
embedded literal M (validated rows from milestone_rows.py + gate flags). A header records the
manifest sha256 + row count + phase/package/gates so the generated file is reproducible/auditable.

Usage:
    python3 meta/make_milestone_workflow.py <phase> <package> [--base-ready] [--g1-ready] [--g2-ready] [--no-g0]
Then launch:   Workflow({ scriptPath: "<printed path>" })   # no args needed
"""
import json, os, re, sys, subprocess, hashlib, datetime

META = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(META, "area_milestone_pipeline.workflow.js")
MANIFEST = os.path.join(META, "opg_corpus_manifest.json")
OUTDIR = os.path.join(META, "generated")
START, END = "// <<MILESTONE-SPEC-START>>", "// <<MILESTONE-SPEC-END>>"

if len(sys.argv) < 3:
    sys.exit("usage: make_milestone_workflow.py <phase> <package> [--base-ready] [--g1-ready] [--g2-ready] [--no-g0]")
phase, package = sys.argv[1], sys.argv[2]
flags = set(sys.argv[3:])
mono = os.path.dirname(META)
pkg_exists = os.path.isdir(os.path.join(mono, package, "theories"))
base_has_v = os.path.isdir(os.path.join(mono, "base", "theories")) and any(
    f.endswith(".v") for _, _, fs in os.walk(os.path.join(mono, "base")) for f in fs)
gates = {
    "g0_ready": pkg_exists and "--no-g0" not in flags,
    "g1_ready": "--g1-ready" in flags,
    "base_ready": base_has_v or "--base-ready" in flags,
    "g2_ready": "--g2-ready" in flags,
}

# 1) validated rows via the deterministic loader (errors out on multi-repo phase, bad ids, etc.)
proc = subprocess.run([sys.executable, os.path.join(META, "milestone_rows.py"), phase, package],
                      capture_output=True, text=True)
if proc.returncode != 0:
    sys.exit(f"milestone_rows.py failed:\n{proc.stderr}")
rows = json.loads(proc.stdout)
if not rows:
    sys.exit(f"no rows for {phase}/{package}")

# 2) manifest provenance
mhash = hashlib.sha256(open(MANIFEST, "rb").read()).hexdigest()
stamp = datetime.datetime.now().strftime("%Y-%m-%d")

# 3) build the embedded literal M and splice it into the template between the markers
tpl = open(TEMPLATE).read()
if START not in tpl or END not in tpl:
    sys.exit("template missing <<MILESTONE-SPEC>> markers")
pre, rest = tpl.split(START, 1); _, post = rest.split(END, 1)
spec = (
    f"{START}  (GENERATED by make_milestone_workflow.py — do not hand-edit)\n"
    f"// manifest sha256={mhash[:16]} | rows={len(rows)} | {phase}/{package} | gates={json.dumps(gates)} | {stamp}\n"
    f"const M = {{ phase: {json.dumps(phase)}, repo: {json.dumps(package)},\n"
    f"  base_ready: {str(gates['base_ready']).lower()}, g0_ready: {str(gates['g0_ready']).lower()}, "
    f"g1_ready: {str(gates['g1_ready']).lower()}, g2_ready: {str(gates['g2_ready']).lower()},\n"
    f"  rows: {json.dumps(rows, ensure_ascii=False)} }}\n"
    f"if (!Array.isArray(M.rows) || M.rows.length === 0) return {{ error: 'generated wrapper: no rows' }}\n"
    f"{END}"
)
header = (
    f"/* GENERATED milestone workflow — {phase}/{package}\n"
    f" * Source: meta/area_milestone_pipeline.workflow.js (template) + meta/milestone_rows.py {phase} {package}\n"
    f" * Manifest: meta/opg_corpus_manifest.json @ sha256 {mhash[:16]} ({len(rows)} rows)\n"
    f" * Gates: {json.dumps(gates)}    Generated: {stamp}\n"
    f" * Regenerate (do not hand-edit): python3 meta/make_milestone_workflow.py {phase} {package}\n"
    f" * Run: Workflow({{ scriptPath: this-file }})  — no runtime args needed. */\n"
)
out_js = header + pre + spec + post

os.makedirs(OUTDIR, exist_ok=True)
out_path = os.path.join(OUTDIR, f"{phase}__{package}.workflow.js")
open(out_path, "w").write(out_js)
print(out_path)
sys.stderr.write(f"generated {phase}/{package}: {len(rows)} rows, gates={gates}, manifest {mhash[:12]}\n")
