#!/usr/bin/env python3
"""Static corpus-status audit report for graph-theory-rocq (the OPG formalization).

Deterministic from the committed sources of truth:
  - meta/opg_corpus_manifest.json  (routing/provenance: slug, title, repo, phase, status, legs)
  - meta/opg_legs_state.json       (leg state + per-row note + commit/package provenance)
  - meta/dependency_graph.json     (the federation edge graph)
  - base/theories/base.v           (the cross-area base surfaces)

Default: regenerate meta/CORPUS_STATUS.md.
`--check`: regenerate in-memory and (1) assert the headline invariants (227 total, 0 todo,
done+partial+blocked == total) and (2) fail on drift vs the committed report — so the public
"statement-complete" claim is machine-backed. No volatile data (timestamps / global HEAD) is
embedded, so the report is stable until the manifest/overlay genuinely change.
"""
import json, os, re, sys

META = os.path.dirname(os.path.abspath(__file__))
MONO = os.path.dirname(META)
OUT = os.path.join(META, "CORPUS_STATUS.md")

NS = {'chromatic-theory': 'Chromatic', 'hamiltonicity-theory': 'Hamilton', 'homomorphism-theory': 'Hom',
      'cycle-theory': 'Cycle', 'minor-theory': 'Minor', 'packing-theory': 'Packing',
      'reconstruction-theory': 'Reconstruction', 'hypergraph-theory': 'Hypergraph',
      'topological-graph-theory': 'Topological', 'graph-theory-misc': 'GTMisc',
      'spectral-graph-theory': 'Spectral', 'extremal-graph-theory': 'Extremal',
      'infinite-graph-theory': 'Infinite', 'digraph-theory': 'Digraph', 'graph-theory-base': 'GTBase'}

manifest = json.load(open(os.path.join(META, "opg_corpus_manifest.json")))
overlay = json.load(open(os.path.join(META, "opg_legs_state.json")))
edges = json.load(open(os.path.join(META, "dependency_graph.json")))
rows = manifest["rows"]
ent = overlay["entries"]
STATES = ["done", "partial", "blocked", "todo"]

def state_of(r):
    return r.get("legs", {}).get("statement", "todo")

def count(rs):
    c = {s: 0 for s in STATES}
    for r in rs:
        c[state_of(r)] = c.get(state_of(r), 0) + 1
    return c

total = len(rows)
overall = count(rows)
attempted = total - overall["todo"]

# base surfaces
base_src = open(os.path.join(MONO, "base", "theories", "base.v")).read()
surfaces = re.findall(r"^(?:Definition|Notation)\s+([A-Za-z_][A-Za-z0-9_']*)", base_src, re.M)
surfaces = [s for s in surfaces if not s.startswith(("box_", "tensor_", "line_", "total_", "pow_",
            "sub_", "reach_", "cyc_", "madj", "lo", "hi", "loopless", "share_", "oedge", "SubVert"))]

def reasons(state):
    out = []
    for r in rows:
        if state_of(r) == state:
            note = (ent.get(r["slug"], {}) or {}).get("note", "")
            out.append((r["repo"], r["slug"], r.get("title", r["slug"]), note))
    return sorted(out)

L = []
w = L.append
w("# graph-theory-rocq — OpenProblemGarden corpus status (statement-complete)\n")
w("> Auto-generated by `meta/report_corpus_status.py`. Verify with "
  "`python3 meta/report_corpus_status.py --check` (drift + invariant gate) after `make gate`.\n")
w("## Headline\n")
w(f"- **{attempted}/{total} rows attempted** ({round(100*attempted/total)}%), **0 todo**.")
w(f"- **{overall['done']} done** (axiom-free `Definition <name>_statement : Prop`, `Print Assumptions` clean) "
  f"· **{overall['partial']} partial** · **{overall['blocked']} blocked**.")
w(f"- Federation: {len([p for p in NS if p not in ('digraph-theory','graph-theory-base')])} area packages "
  f"+ `graph-theory-base` + absorbed `digraph-theory`.\n")

# per-area
w("## Per-area\n")
w("| area (package) | namespace | done | partial | blocked | total |")
w("|---|---|--:|--:|--:|--:|")
by_repo = {}
for r in rows:
    by_repo.setdefault(r["repo"], []).append(r)
for repo in sorted(by_repo):
    c = count(by_repo[repo])
    w(f"| {repo} | {NS.get(repo,'?')} | {c['done']} | {c['partial']} | {c['blocked']} | {len(by_repo[repo])} |")
w(f"| **TOTAL** | | **{overall['done']}** | **{overall['partial']}** | **{overall['blocked']}** | **{total}** |\n")

# per-phase
w("## Per-phase (milestones)\n")
w("| phase | done | partial | blocked | total |")
w("|---|--:|--:|--:|--:|")
by_phase = {}
for r in rows:
    by_phase.setdefault(r.get("phase", "?"), []).append(r)
for ph in sorted(by_phase):
    c = count(by_phase[ph])
    w(f"| {ph} | {c['done']} | {c['partial']} | {c['blocked']} | {len(by_phase[ph])} |")
w("")

# partial / blocked reasons
for state, hdr in [("partial", "Partial — faithful but conditional / needs a deferred layer"),
                   ("blocked", "Blocked — needs a layer deliberately out of scope")]:
    w(f"## {hdr} ({count(rows)[state]})\n")
    w("| area | slug | reason |")
    w("|---|---|---|")
    for repo, slug, title, note in reasons(state):
        w(f"| {repo} | {slug} | {note or '(see area docs)'} |")
    w("")

# base surfaces
w("## Base surfaces (`graph-theory-base`, cross-area primitives)\n")
w("Cross-area primitives every area may reuse (promoted only when ≥2 areas need them):\n")
w("`" + "`, `".join(surfaces) + "`\n")

# edges
t = edges["totals"]
w("## Conjecture dependency graph\n")
w(f"- **{t['edges']} edges** — by status {t['by_status']}, by kind {t['by_kind']}; "
  f"{t['proved_theorems']} Qed-proved relative theorems.")
w("- Verified (Qed-closed, sound) edges:")
for e in edges["edges"]:
    if e["status"] == "verified":
        w(f"  - `{e['from']}` {e['kind']} `{e['to']}` ({', '.join(e['sources'])})")
w("")

# verification
w("## Verifying this claim\n")
w("```sh\nmake gate                                   # builds every LANDED milestone, axiom-free, Print Assumptions clean\n"
  "python3 meta/build_edge_graph.py --check    # edge graph: no drift\n"
  "python3 meta/report_corpus_status.py --check # this report: invariants + no drift\n```\n")
w("Per-row provenance (the commit + package that landed each leg) lives in `meta/opg_legs_state.json`; "
  "routing/source-text provenance in `meta/opg_corpus_manifest.json`.\n")

report = "\n".join(L) + "\n"

if "--check" in sys.argv:
    errs = []
    if total != 227:
        errs.append(f"expected 227 rows, found {total}")
    if overall["todo"] != 0:
        errs.append(f"{overall['todo']} rows still todo (corpus not statement-complete)")
    if overall["done"] + overall["partial"] + overall["blocked"] != total:
        errs.append("done+partial+blocked != total (a row has an unexpected leg state)")
    committed = open(OUT).read() if os.path.exists(OUT) else ""
    if committed != report:
        errs.append("CORPUS_STATUS.md is stale — run `python3 meta/report_corpus_status.py`")
    if errs:
        sys.exit("CORPUS-STATUS GATE FAILED:\n  - " + "\n  - ".join(errs))
    print(f"corpus-status gate OK: {attempted}/{total} attempted, 0 todo; "
          f"{overall['done']} done / {overall['partial']} partial / {overall['blocked']} blocked; no drift")
else:
    open(OUT, "w").write(report)
    print(f"wrote {os.path.relpath(OUT, MONO)}: {attempted}/{total} attempted, "
          f"{overall['done']} done / {overall['partial']} partial / {overall['blocked']} blocked")
