#!/usr/bin/env python3
"""extract_catalog.py — auto-generate the full-catalog appendix
(docs/formal/lemma_catalog.tex) from the .v files in _CoqProject.

One line per named declaration: kind, name (GitHub-linked), file:line,
first sentence of the preceding coqdoc docstring if any. Results that
have a narrative page (the statement-audit catalog of
scripts/statement_closure.py) are starred.

Adapted from mathcomp-eulerian/docs/formal/extract_catalog.py.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from statement_closure import CATALOG  # the featured results

OUTPUT = ROOT / "docs" / "formal" / "lemma_catalog.tex"
GITHUB = "https://github.com/LLM4Rocq/digraph-theory/blob/main"

DECL = re.compile(
    r"^(Definition|Lemma|Theorem|Corollary|Fact|Fixpoint|Inductive|"
    r"Notation|Record)\s+([A-Za-z_][A-Za-z0-9_']*)", re.M)

TEX_ESCAPE = str.maketrans({
    "_": r"\_", "&": r"\&", "%": r"\%", "#": r"\#", "$": r"\$",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}", "\\": r"\textbackslash{}",
})


UNICODE_TEX = {
    "ω̄": r"$\bar\omega$", "ω": r"$\omega$", "ℓ": r"$\ell$",
    "δ": r"$\delta$", "σ": r"$\sigma$", "κ": r"$\kappa$",
    "α": r"$\alpha$", "β": r"$\beta$", "γ": r"$\gamma$",
    "Σ": r"$\Sigma$", "π": r"$\pi$", "ψ": r"$\psi$", "φ": r"$\phi$",
    "≤": r"$\le$", "≥": r"$\ge$", "≠": r"$\ne$", "∈": r"$\in$",
    "∉": r"$\notin$", "⊆": r"$\subseteq$", "∪": r"$\cup$",
    "∩": r"$\cap$", "∖": r"$\setminus$", "×": r"$\times$",
    "→": r"$\to$", "⟹": r"$\Rightarrow$", "⟺": r"$\Leftrightarrow$",
    "⇒": r"$\Rightarrow$", "⇔": r"$\Leftrightarrow$",
    "⊎": r"$\uplus$", "≅": r"$\cong$", "−": "--", "—": "---",
    "–": "--", "…": r"\dots{}", "⌈": r"$\lceil$", "⌉": r"$\rceil$",
    "⌊": r"$\lfloor$", "⌋": r"$\rfloor$", "≺": r"$\prec$",
    "∎": "", "'": "'", "`": "'", "´": "'", "“": "``", "”": "''",
    "·": r"$\cdot$", "∘": r"$\circ$", "₁": "1", "₂": "2",
    "¬": r"$\lnot$", "∧": r"$\land$", "∨": r"$\lor$",
    "∀": r"$\forall$", "∃": r"$\exists$", "ε": r"$\varepsilon$",
    "é": r"\'e", "è": r"\`e",
}


def esc(s: str) -> str:
    s = s.translate(TEX_ESCAPE)
    for u, tex in UNICODE_TEX.items():
        s = s.replace(u, tex)
    # anything still non-ASCII would crash pdflatex: drop it
    return "".join(c for c in s if ord(c) < 128)


def docstring_above(src: str, pos: int) -> str:
    """First sentence of a coqdoc (** ... *) block ending just above."""
    head = src[:pos].rstrip()
    if not head.endswith("*)"):
        return ""
    start = head.rfind("(**")
    if start < 0:
        return ""
    doc = head[start + 3:-2].strip()
    doc = re.sub(r"\s+", " ", doc)
    doc = re.sub(r"\[([^]]*)\]", r"\\texttt{\1}", esc(doc))
    m = re.match(r"(.*?[.!?])(\s|$)", doc)
    return m.group(1) if m else doc[:140]


def main() -> None:
    vfiles = [l.strip() for l in (ROOT / "_CoqProject").read_text().splitlines()
              if l.strip().endswith(".v")]
    out = ["% Auto-generated by scripts/extract_catalog.py — do not edit.",
           ""]
    total = 0
    for vrel in vfiles:
        src = (ROOT / vrel).read_text(encoding="utf-8")
        entries = []
        for m in DECL.finditer(src):
            kind, name = m.group(1), m.group(2)
            if name == "_":
                continue
            line = src[:m.start()].count("\n") + 1
            star = r"$\bigstar$ " if name in CATALOG else ""
            doc = docstring_above(src, m.start())
            doc = f" --- {doc}" if doc else ""
            entries.append(
                f"\\item[{star}\\texttt{{{esc(name)}}}] "
                f"({kind.lower()}) "
                f"\\href{{{GITHUB}/{vrel}\\#L{line}}}"
                f"{{\\texttt{{{esc(vrel.split('/')[-1])}:{line}}}}}{doc}")
        if not entries:
            continue
        total += len(entries)
        out.append(f"\\section*{{\\texttt{{{esc(vrel)}}}}}")
        out.append("\\begin{description}\\setlength\\itemsep{0pt}"
                   "\\small")
        out.extend(entries)
        out.append("\\end{description}")
        out.append("")
    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{total} catalog entries -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
